name: peminjam_perpustakaan_kelas_b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.11
  lottie: ^3.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Smart Library.png
  android: true
  ios: true
  web: true

flutter: 
  uses-material-design: true

assets:
  - assets/Smart Library.png
  - assets/ronaldo.jpg
  - assets/Lottie/


